title: Bibek T # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description Will be here soon
  <br><br>
  Second description Will be here soon
  <br><br>
  <a href="https://www.linkedin.com/in/timalsianbibek">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
